# Generated by Django 3.0.5 on 2020-07-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200731_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='imagem',
            field=models.ImageField(upload_to='textos'),
        ),
    ]
