# Generated by Django 3.0.5 on 2020-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200731_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
