# Generated by Django 3.0.5 on 2020-05-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_editado', models.DateTimeField(auto_now=True)),
                ('posts', models.ManyToManyField(to='backend.Post')),
            ],
        ),
    ]
