# Generated by Django 3.0.5 on 2020-07-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default='NA', upload_to=''),
            preserve_default=False,
        ),
    ]
