# Generated by Django 3.0.5 on 2020-07-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_livro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='imagem',
            field=models.ImageField(default='NA', upload_to='books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(upload_to='books'),
        ),
    ]
